# Generated by Django 3.1.4 on 2020-12-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('item_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('invioce_number', models.CharField(max_length=100)),
                ('seller', models.CharField(max_length=100)),
                ('buyer', models.CharField(max_length=100)),
                ('digitized', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('items', models.ManyToManyField(to='Invoice_data.Item')),
            ],
        ),
    ]
