# Generated by Django 3.1.4 on 2020-12-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice_data', '0002_auto_20201220_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='invioce_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
