# Generated by Django 3.1.4 on 2020-12-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice_data', '0004_auto_20201220_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='digitized',
            field=models.CharField(default='undigitized', max_length=15),
        ),
    ]
