# Generated by Django 3.1.4 on 2020-12-20 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice_data', '0006_auto_20201220_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoices',
            old_name='digitized',
            new_name='status',
        ),
    ]
